---
plugin: servicenow.itsm.now

table: cmdb_ci_linux_server

fields:
  - name
  - host_name
  - ip_address
  - os
  - ram
  - cpu_count
  - sys_class_name
  - operational_status
  - environment
  - short_description

selection_order: host_name,name,ip_address

columns:
  - host_name: name
  - ip_address: ansible_host
  - os: os
  - sys_class_name: classification

compose:
  ansible_host: ip_address

groups:
  linux: sys_class_name == "cmdb_ci_linux_server"
  rhel: "'Red Hat' in os"

keyed_groups:
  - key: environment | default("unknown") | lower
    prefix: env
    separator: "_"
