---
repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        exclude: >
          (?x)^(
            .config/dictionary.txt|
            examples/broken/encoding.j2|
            test/schemas/negative_test/.*|
            test/schemas/test/.*|
            src/ansiblelint/schemas/.*\.json
          )$
        additional_dependencies:
          - tomli
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.24.2
    hooks:
      - id: toml-sort-fix
        alias: toml

  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: 1.6.0
    hooks:
      - id: tox-ini-fmt

  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
        # ignore formatting-prettier to have an accurate prettier comparison
        exclude: >
          (?x)^(
            test/eco/.*.result|
            examples/yamllint/.*|
            test/fixtures/formatting-before/.*|
            test/fixtures/formatting-prettier/.*
          )$
      - id: trailing-whitespace
        exclude: >
          (?x)^(
            examples/playbooks/(with-skip-tag-id|unicode).yml|
            examples/playbooks/example.yml|
            examples/yamllint/.*|
            test/eco/.*.result|
            test/fixtures/formatting-before/.*
          )$
      - id: mixed-line-ending
      - id: fix-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
        language_version: python3
...
