---
- name: Deploy Ansible Automation Portal
  hosts: localhost
  # Required extra vars:
  #   controller_host: https://my-aap-deployment.example.com
  #   controller_username: admin
  #   controller_password: SomePassword
  #
  # Optional extra vars:
  #   github_token: ghp_xxxx
  #   gitlab_token: glpat-xxxx
  #   openshift_namespace: self-service
  roles:
    - self-service
