---
- name: test
  hosts: localhost
  tasks:
    - name: Build CNV storage class
      kubernetes.core.k8s:
        wait: true
        state: "present"
        definition:
          kind: StorageClass
          apiVersion: storage.k8s.io/v1
          metadata:
            name: virt-gp3-csi
            annotations:
              storageclass.kubevirt.io/is-default-virt-class: 'true'
          provisioner: ebs.csi.aws.com
          parameters:
            encrypted: 'true'
            type: gp3
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          volumeBindingMode: Immediate

