---
- name: Do tony things
  hosts: localhost
  tasks:
    - name: Slurp creds
      ansible.builtin.include_role:
        name: aro_creds
      vars:
        aro_creds_file_path: "{{ playbook_dir }}/aro.creds"

    - name: Include it
      ansible.builtin.include_role:
        name: clab
