---
- name: Do tony things
  hosts: localhost
  tasks:
    - name: Slurp creds
      ansible.builtin.include_role:
        name: aro_creds
      vars:
        creds_file_path: "{{ playbook_dir }}/aro.creds" # noqa: var-naming[no-role-prefix]

    - name: Include it
      ansible.builtin.include_role:
        name: clab
