---
- name: Bootstrap APD
  block:
    - name: Check out product-demos-postinstall repo
      ansible.builtin.git:
        repo: '{{ controller_postinstall_repo_url }}'
        dest: '{{ controller_postinstall_dir }}'
        version: '{{ controller_postinstall_repo_ref }}'
        force: true

    - name: Include product-demos-postinstall variables
      ansible.builtin.include_vars:
        dir: '{{ controller_postinstall_dir }}'
        extensions:
          - yml
          - yaml
        ignore_files: '{{ controller_postinstall_ignore_files }}'
        ignore_unknown_extensions: true

    - name: Execute automation controller resource configuration
      ansible.builtin.include_role:
        name: infra.controller_configuration.dispatch

    - name: Print user message
      ansible.builtin.debug:
        msg: "{{ user_message }}"
      when: user_message is defined
...
