---
collections:
  - name: ansible.controller
    version: ">=4.6.0"
  - name: ansible.platform
    version: ">=2.5.0"
  - name: infra.aap_configuration
  - name: kubernetes.core
    version: ">=6.1.0"
  - name: community.general
    version: "9.5.0"
