---
collections:
  # AAP config as code
  - name: ansible.controller
    version: ">=4.6.0"
  - name: ansible.platform
    version: ">=2.5.0"
  - name: infra.ah_configuration
    version: ">=2.0.6"
  - name: infra.controller_configuration
    version: ">=2.11.0"
  - name: infra.aap_configuration
