---
version: 3
images:
  base_image:
    name: 'registry.redhat.io/ansible-automation-platform-25/ee-minimal-rhel9:latest'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system:
    - python3.11-devel [platform:rpm]
    - systemd-devel
    - gcc

additional_build_files:
  - src: ansible.cfg
    dest: configs

options:
  package_manager_path: /usr/bin/microdnf

additional_build_steps:
  prepend_base:
    - ARG OPENSHIFT_CLIENT_RPM
    - RUN $PKGMGR -y update && $PKGMGR install -y bash-completion && $PKGMGR clean all
    - RUN curl -o /tmp/openshift-clients.rpm $OPENSHIFT_CLIENT_RPM && rpm -Uvh /tmp/openshift-clients.rpm && rm -f /tmp/openshift-clients.rpm
  prepend_galaxy:
    - ADD _build/configs/ansible.cfg /etc/ansible/ansible.cfg
    - ARG ANSIBLE_GALAXY_SERVER_CERTIFIED_TOKEN
    - ARG ANSIBLE_GALAXY_SERVER_VALIDATED_TOKEN
  append_final:
    - RUN rm -rf /usr/libexec/platform-python
          && ln -s /usr/bin/python3.9 /usr/libexec/platform-python
