---
collections:
  - name: azure.azcollection
    version: "3.9.0"
  - name: ansible.controller
  - name: infra.aap_configuration
  - name: kubernetes.core
  - name: containers.podman
  - name: community.general
    version: "9.5.0"
