---
aap_organizations:
  - name: "Red Hat network organization"

controller_inventories:
  - name: "Workshop Inventory"
    organization: "Red Hat network organization"

controller_hosts:
  - name:
    inventory: "Workshop Inventory"
    enabled: true
    variables:
      ansible_user: admin
      ansible_password: Admin_1234!
      ansible_network_os: cisco.nxos.nxos
      ansible_connection: ansible.netcommon.network_cli
      ansible_host: sandbox-nxos-1.cisco.com

controller_groups:
  - name: switches
    hosts:
      - nxos
    variables:
      ansible_connection: network_cli
      ansible_network_os: cisco.ios.ios
    inventory: "Workshop Inventory"

  - name: cisco
    variables:
      ansible_connection: network_cli
      ansible_network_os: cisco.ios.ios
    inventory: "Workshop Inventory"
