---
- name: Configure 'AWS with ROSA Open Environment' for Ansible Product-Demos with OCP-V
  hosts: localhost
  tasks:
    - name: Warning this may incur high costs
      ansible.builtin.pause:
        prompt: "This may incur high costs, please acknowledge responsibility"
      when:
        - ignore_prompt is not defined

    - name: Parse credentials
      ansible.builtin.include_role:
        name: rosa_creds
      vars:
        rosa_creds_file_path: "{{ playbook_dir }}/{{ creds_file | default('../aws.creds') }}"
        rosa_creds_user_file_path: "{{ playbook_dir }}/{{ user_creds_file | default('../user.creds') }}"

    - name: Add ROSA bastion to inventory
      ansible.builtin.add_host:
        name: "{{ rosa_bastion_host }}"
        groups: "rosa"
        ansible_password: "{{ rosa_bastion_password }}"
        ansible_user: "rosa"

    - name: Get OC login status
      ansible.builtin.command: "oc whoami" # noqa: no-changed-when
      register: oc_whoami
      ignore_errors: true

    - name: Reset ROSA cluster-admin
      when: 
        - (oc_whoami is failed) or (openshift_console_url not in oc_whoami.stdout)
      delegate_to: "{{ groups['rosa'] | first }}"
      block:
        - name: Get the list of ROSA clusters
          ansible.builtin.command: "rosa list cluster -o json"
          register: rosa_cluster_list
          changed_when: false
          failed_when: rosa_cluster_list.rc != 0
          check_mode: false

        - name: Set cluster_name fact from the output
          ansible.builtin.set_fact:
            cluster_name: "{{ (rosa_cluster_list.stdout | from_json)[0]['name'] }}"
            rosa_availability_zone: "{{ (rosa_cluster_list.stdout | from_json)[0]['nodes']['availability_zones'][0] }}"

        - name: Display the extracted cluster name (for debugging)
          ansible.builtin.debug:
            msg: "Found cluster name: {{ cluster_name }}"
          when:
            - "ansible_debug is defined"
            - "ansible_debug"

        - name: Delete the admin user on the specified cluster
          ansible.builtin.command: "rosa delete admin -c {{ cluster_name }} --yes"
          register: rosa_admin_creation
          changed_when: "'Admin user created' in rosa_admin_creation.stdout"
          ignore_errors: true

        - name: Create the admin user on the specified cluster
          ansible.builtin.command: "rosa create admin -c {{ cluster_name }} -p {{ openshift_admin_password }}"
          register: rosa_admin_creation
          changed_when: "'Admin user created' in rosa_admin_creation.stdout"

        - name: Extract the 'oc login' command line from the output
          ansible.builtin.set_fact:
            login_command_line: "{{ rosa_admin_creation.stdout_lines | select('match', '.*oc login.*') | first | trim }}"
          when: "'oc login' in rosa_admin_creation.stdout"

        - name: Set credential facts from the login command
          ansible.builtin.set_fact:
            rosa_url: "{{ login_command_line.split()[2] }}"
            rosa_username: "{{ login_command_line.split()[4] }}"
            rosa_password: "{{ login_command_line.split()[6] }}"
          when: login_command_line is defined and login_command_line != ""

    - name: Do local tasks if login required
      when:
        - (oc_whoami is failed) or (openshift_console_url not in oc_whoami.stdout)
      block:
        - name: Login to OCP Cluster with new credentials
          ansible.builtin.command: "{{ login_command_line }}"
          register: oc_login
          changed_when: "'Login successful' in oc_login.stdout"
          retries: 30
          delay: 5

    - name: Determine metal node availability
      delegate_to: "{{ groups['rosa'] | first }}"
      block:
        - name: Get the list of ROSA clusters
          ansible.builtin.command: "rosa list cluster -o json"
          register: rosa_cluster_list
          changed_when: false
          failed_when: rosa_cluster_list.rc != 0
          check_mode: false

        - name: Set cluster_name fact from the output
          ansible.builtin.set_fact:
            cluster_name: "{{ (rosa_cluster_list.stdout | from_json)[0]['name'] }}"
            rosa_availability_zone: "{{ (rosa_cluster_list.stdout | from_json)[0]['nodes']['availability_zones'][0] }}"

        - name: Get machinepools
          ansible.builtin.command: "rosa list machinepool --cluster={{ cluster_name }} -o json" # noqa: no-changed-when
          register: machinepools

        - name: Add virt machinepool
          ansible.builtin.command: "rosa create machinepool --cluster={{ cluster_name }} --replicas 1 --availability-zone={{ rosa_availability_zone }}
          --instance-type m5zn.metal  --name rosa-virt" # noqa: no-changed-when
          when: machinepools.stdout | from_json | length < 2

    - name: Deploy AAP 2.5+ Operator
      ansible.builtin.include_role:
        name: 'aap_operator'
        tasks_from: workload
      vars:
        aap_operator_controller_admin_password: "{{ aap_admin_password }}"
        aap_operator_inject_manifest: true
        aap_operator_inject_manifest_path: "{{ aap_manifest_path }}"
        aap_operator_catalog_snapshot_image_tag: "{{ olm_tag | default('v4.19_2025_08_25') }}"

    - name: Ansible Product-Demos Bootstrap
      ansible.builtin.include_role:
        name: 'apd'

    - name: Show bearer token
      ansible.builtin.command: "oc whoami --show-token" # noqa: no-changed-when
      register: oc_whoami
      ignore_errors: true

    - name: Set OCP bearer token
      ansible.builtin.set_fact:
        openshift_bearer_token: "{{ oc_whoami.stdout }}"

    - name: Configure credentials we are aware of
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch
      vars:
        controller_credentials:
          - name: Demo Credential
            credential_type: Machine
            update_secrets: true
            inputs:
              username: "admin"
              password: "{{ aap_machine_cred_password }}"
              ssh_key_data: "{{ aap_machine_cred_priv_key }}"

          - name: AWS
            credential_type: Amazon Web Services
            organization: Default
            inputs:
              username: "{{ aws_access_key }}"
              password: "{{ aws_secret_key }}"

          - name: OpenShift Credential
            credential_type: "OpenShift or Kubernetes API Bearer Token"
            organization: Default
            inputs:
              host: "{{ openshift_api_url }}"
              bearer_token: "{{ openshift_bearer_token }}"

        controller_launch_jobs:
          - name: "Product Demos | Single demo setup"
            wait: true
            extra_vars:
              demo: "openshift"

          - name: "OpenShift / CNV / Install Operator"
            wait: true

    - name: Build CNV storage class
      kubernetes.core.k8s:
        wait: true
        state: "present"
        definition:
          kind: StorageClass
          apiVersion: storage.k8s.io/v1
          metadata:
            name: virt-gp3-csi
            annotations:
              storageclass.kubevirt.io/is-default-virt-class: 'true'
          provisioner: ebs.csi.aws.com
          parameters:
            encrypted: 'true'
            type: gp3
          reclaimPolicy: Delete
          allowVolumeExpansion: true
          volumeBindingMode: Immediate

    - name: Wait if metal node is still coming up
      delegate_to: "{{ groups['rosa'] | first }}"
      block:
        - name: Wait until virt hosts comes up
          ansible.builtin.command: "rosa list machinepool --cluster={{ cluster_name }} -o json"
          register: machinepools
          changed_when: false
          until: >
            (machinepools.stdout | from_json
            | selectattr('id', 'equalto', 'rosa-virt')
            | list)[0].status.current_replicas == 1
          retries: 75
          delay: 20
...
