---
- name: Build Azure resources
  ansible.builtin.include_tasks: azure.yml

- name: Do rootful things (this is so ugly)
  ansible.builtin.include_tasks: podman.yml
  run_once: true
  args:
    apply:
      become: true
      delegate_to: clab

- name: Deploy containers (this is so ugly)
  ansible.builtin.include_tasks: config.yml
  run_once: true
  args:
    apply:
      become: false
      delegate_to: clab
