---
- name: Deploy Ansible Automation Platform on ARO
  hosts: localhost
  vars:
    aap_operator_disable_lightspeed: false
    aro_creds_file_path: "{{ playbook_dir }}/../aro.creds.yml"
  tasks:
    - name: Slurp ARO credentials
      ansible.builtin.include_role:
        name: aro_creds

    - name: Slurp user credentials
      ansible.builtin.include_role:
        name: user_creds

    - name: Get OC login status
      ansible.builtin.command: "oc whoami --show-server=true" # noqa: no-changed-when
      register: oc_whoami
      ignore_errors: true

    - name: Login to ARO cluster if needed
      when:
        - (oc_whoami is failed) or (openshift_console_url not in oc_whoami.stdout)
      block:
        - name: Login to OCP Cluster with credentials
          ansible.builtin.command: >-
            oc login --username=kubeadmin
            --password={{ openshift_kubeadmin_password }}
            {{ openshift_api_url }}
          register: oc_login
          changed_when: "'Login successful' in oc_login.stdout"

    - name: Deploy AAP Operator
      ansible.builtin.include_role:
        name: 'aap_operator'
        tasks_from: workload
      vars:
        aap_operator_controller_admin_password: "{{ aap_admin_password }}"
        aap_operator_inject_manifest: true
        aap_operator_inject_manifest_path: "{{ aap_manifest_path }}"

    - name: Display Access info
      ansible.builtin.debug:
        msg:
          - "AAP URL: {{ aap_controller_web_url }}"
          - "AAP Admin Login: {{ aap_controller_admin_user }}"
          - "AAP Admin Password: {{ aap_operator_controller_admin_password }}"
...
