---
- name: Configure 'Azure with ARO Open Environment (Subscription Based)' with Ansible Product-Demos and ContainerLab
  hosts: localhost
  vars:
    aap_operator_disable_lightspeed: false
    aro_creds_file_path: "{{ playbook_dir }}/{{ creds_file | default('../aro.creds') }}"
    aro_creds_require_pub_key: true
  tasks:
    - name: Slurp credentials
      ansible.builtin.include_role:
        name: aro_creds

    - name: Slurp credentials
      ansible.builtin.include_role:
        name: user_creds

    - name: Get OC login status
      ansible.builtin.command: "oc whoami --show-server=true" # noqa: no-changed-when
      register: oc_whoami
      ignore_errors: true

    - name: Do local tasks if login required
      when:
        - (oc_whoami is failed) or (openshift_console_url not in oc_whoami.stdout)
      block:
        - name: Login to OCP Cluster with credentials
          ansible.builtin.command: "oc login --username=kubeadmin --password={{ openshift_kubeadmin_password }} {{ openshift_api_url }}"
          register: oc_login
          changed_when: "'Login successful' in oc_login.stdout"

    - name: Deploy AAP 2.5+ Operator
      ansible.builtin.include_role:
        name: 'aap_operator'
        tasks_from: workload
      vars:
        aap_operator_controller_admin_password: "{{ aap_admin_password }}"
        aap_operator_inject_manifest: true
        aap_operator_inject_manifest_path: "{{ aap_manifest_path }}"
        aap_operator_catalog_snapshot_image_tag: "v4.19_2025_07_21"

    - name: Show bearer token
      ansible.builtin.command: "oc whoami --show-token" # noqa: no-changed-when
      register: oc_whoami
      ignore_errors: true

    - name: Set OCP bearer token
      ansible.builtin.set_fact:
        openshift_bearer_token: "{{ oc_whoami.stdout }}"

    - name: Deploy container lab
      ansible.builtin.include_role:
        name: "clab"
      vars:
        clab_topology_deployment: "rhdp"

    - name: Run multi-vendor network workshop config as code
      ansible.builtin.include_role:
        name: "mvnw"

    - name: Configure credentials we are aware of
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch
      vars:
        controller_credentials:
          - name: Demo Credential
            credential_type: Machine
            update_secrets: true
            inputs:
              username: "admin"
              password: "{{ aap_machine_cred_password }}"
              ssh_key_data: "{{ aap_machine_cred_priv_key }}"

          - name: Azure
            credential_type: Microsoft Azure Resource Manager
            organization: Default
            inputs:
              subscription: "{{ azure_subscription }}"
              username: "{{ azure_resourcegroup }}"
              password: "{{ azure_password }}"
              secret: "{{ azure_password }}" # seems redundant but maybe works?
              tenant: "{{ azure_tenant }}"
              client: "{{ azure_client_id }}"

          - name: OpenShift Credential
            credential_type: "OpenShift or Kubernetes API Bearer Token"
            organization: Default
            inputs:
              host: "{{ openshift_api_url }}"
              bearer_token: "{{ openshift_bearer_token }}"


    - name: (Re-)Display Access info
      ansible.builtin.debug:
        msg:
          - "Automation Controller URL: {{ aap_controller_web_url }}"
          - "Automation Controller Admin Login: {{ aap_controller_admin_user }}"
          - "Automation Controller Admin Password: {{ aap_operator_controller_admin_password }}"
...
