---
# override these in job template extra vars if needed
apd_ee_image_version: '25'
apd_ee_image: quay.io/ansible-product-demos/apd-ee-{{ apd_ee_image_version }}:latest
apd_git_repo: https://github.com/ansible/product-demos
apd_git_repo_branch: main
apd_verify_ssl: false

controller_validate_certs: false
controller_configuration_async_delay: 3

controller_credentials:
  - name: Automation Hub
    organization: Default
    credential_type: Ansible Galaxy/Automation Hub API Token
    update_secrets: false
    inputs:
      url: https://console.redhat.com/api/automation-hub/
      auth_url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token

  - name: Controller Credential
    organization: Default
    credential_type: Red Hat Ansible Automation Platform
    update_secrets: false
    state: exists
    inputs:
      host: https://{{ groups.automationcontroller[0] | default('REPLACEME') }}
      username: admin
      password: '{{ controller_admin_password | default("REPLACEME") }}'
      verify_ssl: '{{ apd_verify_ssl }}'

controller_execution_environments:
  - name: Product Demos EE
    image: '{{ apd_ee_image }}'

controller_organizations:
  - name: Default
    galaxy_credentials:
      - Ansible Galaxy
      - Automation Hub

controller_projects:
  - name: Ansible Product Demos
    organization: Default
    scm_type: git
    scm_url: '{{ apd_git_repo }}'
    scm_branch: '{{ apd_git_repo_branch }}'
    default_environment: Product Demos EE
    wait: true

controller_templates:
  - name: "Product Demos | Single demo setup"
    job_type: run
    inventory: Demo Inventory
    project: Ansible Product Demos
    playbook: setup_demo.yml
    credentials: Controller Credential
    execution_environment: Product Demos EE
    allow_simultaneous: true
    survey_enabled: true
    survey_spec:
      name: ''
      description: ''
      spec:
        - type: multiplechoice
          question_name: Demo Category
          variable: demo
          required: true
          choices:
            - linux
            - windows
            - cloud
            - network
            - openshift
            - satellite

  - name: "Product Demos | Multi-demo setup"
    project: Ansible Product Demos
    playbook: multi_select_setup.yml
    inventory: Demo Inventory
    credentials: Controller Credential
    execution_environment: Product Demos EE
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: "Which demos do you want to configure?"
          type: multiselect
          variable: demos
          required: true
          default: "cloud\nlinux\nnetwork\nopenshift\nwindows"
          choices:
            - cloud
            - linux
            - network
            - openshift
            - satellite
            - windows

...
