controller_credentials:
  - name: Automation Hub
    organization: Default
    credential_type: Ansible Galaxy/Automation Hub API Token
    update_secrets: false
    inputs:
      url: https://console.redhat.com/api/automation-hub/
      auth_url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token

  - name: Controller Credential
    organization: Default
    credential_type: Red Hat Ansible Automation Platform
    update_secrets: false
    state: exists
    inputs:
      host: "{{ aap_hostname }}"
      username: "{{ aap_username }}"
      password: "{{ aap_password }}"
      verify_ssl: "{{ apd_verify_ssl }}"

controller_execution_environments:
  - name: Product Demos EE
    image: '{{ apd_ee_image }}'

gateway_organizations:
  - name: Default
    galaxy_credentials:
      - Ansible Galaxy
      - Automation Hub

controller_projects:
  - name: Ansible Product Demos
    organization: Default
    scm_type: git
    scm_url: "https://github.com/l3acon/product-demos"
    scm_branch: "cnv_fixes3"
    default_environment: Product Demos EE
    wait: true

controller_templates:
  - name: "Product Demos | Single demo setup"
    job_type: run
    inventory: Demo Inventory
    project: Ansible Product Demos
    playbook: setup_demo.yml
    credentials: Controller Credential
    execution_environment: Product Demos EE
    allow_simultaneous: true
    survey_enabled: true
    survey_spec:
      name: ''
      description: ''
      spec:
        - type: multiplechoice
          question_name: Demo Category
          variable: demo
          required: true
          choices:
            - linux
            - windows
            - cloud
            - network
            - openshift
            - satellite

  - name: "Product Demos | Multi-demo setup"
    project: Ansible Product Demos
    playbook: multi_select_setup.yml
    inventory: Demo Inventory
    credentials: Controller Credential
    execution_environment: Product Demos EE
    survey_enabled: true
    survey:
      name: ''
      description: ''
      spec:
        - question_name: "Which demos do you want to configure?"
          type: multiselect
          variable: demos
          required: true
          default: "cloud\nlinux\nnetwork\nopenshift\nwindows"
          choices:
            - cloud
            - linux
            - network
            - openshift
            - satellite
            - windows
